version: "3"

services:
  db:
    build: db

  py-srv:
    build: py-srv
    ports:
      - "80:8050"
    depends_on:
      - db
    links:
      - "db:db"
    command: sh -c "/wait && python /app/app.py"
    environment:
      - WAIT_HOSTS=db:1433
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
